name: "吾爱破解签到"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10,18  * * *"
  watch:
    types: [started]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: '代码检查'
        uses: actions/checkout@v2
      - name: '初始化Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
      - name: '安装依赖包'
        run: |
          python -m pip install --upgrade requests
          pip install beautifulsoup4
      - name: '开始签到'
        env:
          POJIE: ${{ secrets.POJIE }}
        run: python main.py
